name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libffi-dev \
          libssl-dev \
          openjdk-8-jdk \
          unzip \
          zip \
          zlib1g-dev \
          libstdc++6 \
          libffi-dev \
          libsqlite3-dev \
          libbz2-dev \
          liblzma-dev \
          libreadline-dev \
          libssl-dev \
          libgdbm-dev \
          libnss3-dev \
          libsqlite3-dev \
          libffi-dev \
          liblzma-dev \
          libbz2-dev \
          libreadline-dev \
          libncursesw5-dev \
          libgdbm-dev \
          libdb5.3-dev \
          libexpat1-dev \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          libbz2-dev \
          liblzma-dev \
          libreadline-dev \
          libncursesw5-dev \
          libgdbm-dev \
          libdb5.3-dev \
          libexpat1-dev \
          libffi-dev \
          libssl-dev
        python -m pip install --upgrade pip
        pip install --upgrade buildozer cython python-for-android

    - name: Setup Android SDK
      run: |
        mkdir -p $HOME/Android/Sdk
        cd $HOME/Android/Sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/
        export ANDROID_SDK_ROOT=$HOME/Android/Sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses
    - name: Install python-for-android explicitly
      run: |
        pip install --upgrade python-for-android

    - name: Build APK
      run: |
        buildozer android update
        buildozer android clean
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: banana-leaf-disease-scanner-apk
        path: bin/*.apk

        
