name: Build

on:
  push:
    branches: [ main, master ]  # Specify your main branches here

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .  # Since the app files are in the root directory
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@latest  # Use the latest version to avoid deprecation issues
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
