name: Build

on:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .  # Your application files are in the root directory
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@4  # Ensure correct version
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}  # Confirm this output is correct
