name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libffi-dev \
          libssl-dev \
          openjdk-11-jdk \
          unzip \
          zip \
          zlib1g-dev \
          libstdc++6 \
          libsqlite3-dev \
          libbz2-dev \
          liblzma-dev \
          libreadline-dev \
          libgdbm-dev \
          libncursesw5-dev \
          libexpat1-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade buildozer cython python-for-android

    - name: Setup Android SDK
      run: |
        mkdir -p $HOME/Android/Sdk
        cd $HOME/Android/Sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        rm cmdline-tools.zip
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        export ANDROID_SDK_ROOT=$HOME/Android/Sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"
        sdkmanager --install "ndk;25.2.9519653"

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/Android/Sdk
        export ANDROID_NDK_HOME=$HOME/Android/Sdk/ndk/25.2.9519653
        buildozer init
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: banana-leaf-disease-scanner-apk
        path: bin/*.apk
